# Generated by Django 3.2.4 on 2021-06-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='gambar',
            field=models.ImageField(upload_to='data_latih/'),
        ),
    ]
