# Generated by Django 3.2.4 on 2021-06-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('entropi', models.FloatField()),
                ('energi', models.FloatField()),
                ('homogenitas', models.FloatField()),
                ('kontras', models.FloatField()),
                ('status', models.IntegerField()),
                ('uji', models.IntegerField()),
                ('gambar', models.CharField(max_length=100)),
            ],
        ),
    ]
