# Generated by Django 3.2.4 on 2021-06-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mata', '0002_alter_data_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='gambar',
            field=models.CharField(max_length=100),
        ),
    ]
